const { generateId, generarFechaActual, generarHoraActual } = require('./generadorId');

const inventarioInicial = [
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 1,
    estadoCilindroId: 1,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 1,
    estadoCilindroId: 2,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 1,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 1,
    estadoCilindroId: 4,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 2,
    estadoCilindroId: 1,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 2,
    estadoCilindroId: 2,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 2,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 2,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 2,
    estadoCilindroId: 4,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 3,
    estadoCilindroId: 1,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 3,
    estadoCilindroId: 2,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 3,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 3,
    estadoCilindroId: 4,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 4,
    estadoCilindroId: 1,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 4,
    estadoCilindroId: 2,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 4,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 4,
    estadoCilindroId: 4,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 5,
    estadoCilindroId: 1,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 5,
    estadoCilindroId: 2,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 5,
    estadoCilindroId: 3,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    cantidad: 0,
    tipoCilindroId: 5,
    estadoCilindroId: 4,
  },
];

const VentasInicial = [
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    tipoCilindroId: 1,
    cantidad: 0,
    valor: 0,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    tipoCilindroId: 2,
    cantidad: 0,
    valor: 0,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    tipoCilindroId: 3,
    cantidad: 0,
    valor: 0,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    tipoCilindroId: 4,
    cantidad: 0,
    valor: 0,
  },
  {
    id: generateId(),
    fecha: generarFechaActual(),
    hora: generarHoraActual(),
    tipoCilindroId: 5,
    cantidad: 0,
    valor: 0,
  },
];

const tipoCilindros = [
  { id: 1, tipo: '5kg' },
  { id: 2, tipo: '11kg' },
  { id: 3, tipo: '15kg' },
  { id: 4, tipo: '45kg' },
  { id: 5, tipo: 'H15' },
];

const estadoCilindros = [
  { id: 1, tipo: 'Lleno' },
  { id: 2, tipo: 'Vacío' },
  { id: 3, tipo: 'Fallad' },
  { id: 4, tipo: 'Prestado' },
];

module.exports = {
  inventarioInicial,
  tipoCilindros,
  estadoCilindros,
  VentasInicial,
};
